<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Berita extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id' => ['type' => 'int', 'constraint' => 11, 'unsigned' => true, 'auto_increment' => true],
            'judul' => ['type' => 'char', 'constraint' => 255, 'null' => false],
            'slug' => ['type' => 'char', 'constraint' => 255, 'null' => false],
            'gambar' => ['type' => 'char', 'constraint' => 100, 'null' => false],
            'redaksi_foto' => ['type' => 'text', 'constraint' => 0, 'null' => true],
            'body' => ['type' => 'text', 'constraint' => 0, 'null' => false],
            'tanggal' => ['type' => 'datetime', 'constraint' => 0, 'null' => false],
            'user_id' => ['type' => 'int', 'constraint' => 6, 'unsigned' => true, 'null' => false],
            'skpd_id' => ['type' => 'int', 'constraint' => 6, 'unsigned' => true, 'null' => false],
            'editor' => ['type' => 'int', 'constraint' => 3, 'null' => true],
            'redaktur' => ['type' => 'int', 'constraint' => 3, 'null' => true],
            'tag' => ['type' => 'char', 'constraint' => 160, 'null' => true],
            'status' => ['type' => 'int', 'constraint' => 2, 'null' => true],
            'pesan' => ['type' => 'text', 'null' => true],
            'created_at' => ['type' => 'date', 'constraint' => 0, 'null' => true],
            'updated_at' => ['type' => 'date', 'constraint' => 0, 'null' => true],
            'deleted_at' => ['type' => 'date', 'constraint' => 0, 'null' => true],
        ]);
        $this->forge->addKey('id', true);
        $this->forge->createTable('berita', true);
    }

    public function down()
    {
        $this->forge->dropTable('berita', true);
    }
}
/* End of file BeritaM.php */
/* Location: ./app/models/BeritaM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-31 04:44:35 */