<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Skpd extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id' => ['type' => 'int', 'constraint' => 6, 'unsigned' => true, 'auto_increment' => true],
			'kode' => ['type' => 'int', 'constraint' => 3, 'null' => false],
			'nama' => ['type' => 'varchar', 'constraint' => 255, 'null' => false],
			'alias' => ['type' => 'char', 'constraint' => 150, 'null' => false],
			'created_at' => ['type' => 'date', 'constraint' => 0, 'null' => true],
			'updated_at' => ['type' => 'date', 'constraint' => 0, 'null' => true],
			'deleted_at' => ['type' => 'date', 'constraint' => 0, 'null' => true],
        ]);        
        $this->forge->addKey('id', true);
        $this->forge->createTable('skpd', true);
    }

    public function down()
    {
        $this->forge->dropTable('skpd', true);
    }
}
/* End of file SkpdM.php */
/* Location: ./app/models/SkpdM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-30 08:08:50 */