<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Users extends Migration
{
	public function up()
	{
		$this->forge->addField([
			'id' => ['type' => 'int', 'constraint' => 6, 'unsigned' => true, 'auto_increment' => true],
			'ip_address' => ['type' => 'varchar', 'constraint' => 45, 'null' => false],
			'username' => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'password' => ['type' => 'varchar', 'constraint' => 255, 'null' => false],
			'email' => ['type' => 'varchar', 'constraint' => 254, 'null' => false],
			'activation_selector' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
			'activation_code' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
			'forgotten_password_selector' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
			'forgotten_password_code' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
			'forgotten_password_time' => ['type' => 'int', 'constraint' => 11, 'null' => true],
			'remember_selector' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
			'remember_code' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
			'created_on' => ['type' => 'int', 'constraint' => 11, 'null' => false],
			'last_login' => ['type' => 'int', 'constraint' => 11, 'null' => true],
			'active' => ['type' => 'tinyint', 'constraint' => 1, 'null' => true],
			'nama_user' => ['type' => 'varchar', 'constraint' => 50, 'null' => true],
			'img' => ['type' => 'varchar', 'constraint' => 50, 'null' => true],
			'phone' => ['type' => 'varchar', 'constraint' => 20, 'null' => true],
		]);
		$this->forge->addKey('id', true);
		$this->forge->createTable('users', true);
	}

	public function down()
	{
		$this->forge->dropTable('users', true);
	}
}
/* End of file UsersM.php */
/* Location: ./app/models/UsersM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-30 08:15:02 */