<?php

namespace App\Controllers;

use App\Models\PosisiM;

class Posisi extends BaseController
{
    protected $posisim;
    function __construct()
    {
        $this->posisim = new PosisiM();
    }
    public function index()
    {
        $this->data = array('title' => 'Posisi | Admin', 'breadcome' => 'Posisi', 'url' => 'posisi/', 'm_posisi' => 'active', 'session' => $this->session);

        echo view('App\Views\posisi\posisi_list', $this->data);
    }

    public function ajax_request()
    {
        $list = $this->posisim->get_datatables();
        $data = array();
        $no = isset($_GET['offset']) ? $_GET['offset'] + 1 : 1;
        foreach ($list as $rows) {
            $row = array();
            $row['id'] = $rows->id;
            $row['nomor'] = $no++;
            $row['nama_posisi'] = $rows->nama_posisi;
            $data[] = $row;
        }
        $output = array(
            "total" => $this->posisim->total(),
            "totalNotFiltered" => $this->posisim->countAllResults(),
            "rows" => $data,
        );
        echo json_encode($output);
    }
    public function create()
    {
        $this->data = array('action' => 'insert', 'btn' => '<i class="fas fa-save"></i> Save');
        $num_of_row = $this->request->getPost('num_of_row');
        for ($x = 1; $x <= $num_of_row; $x++) {
            $data['nama'] = 'Data ' . $x;
            $this->data['form_input'][] = view('App\Views\posisi\form_input', $data);
        }
        $status['html']         = view('App\Views\posisi\form_modal', $this->data);
        $status['modal_title']  = 'Tambah Data Posisi';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function edit()
    {
        $id = $this->request->getPost('id');
        $this->data = array('action' => 'update', 'btn' => '<i class="fas fa-edit"></i> Edit');
        foreach ($id as $ids) {
            $get = $this->posisim->find($ids);
            $data = array(
                'nama' => '<b>' . $get->nama_posisi . '</b>',
                'get' => $get,
            );
            $this->data['form_input'][] = view('App\Views\posisi\form_input', $data);
        }
        $status['html']         = view('App\Views\posisi\form_modal', $this->data);
        $status['modal_title']  = 'Update Data Posisi';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function save()
    {
        switch ($this->request->getPost('action')) {
            case 'insert':
                $nama = $this->request->getPost('id');
                $data = array();
                foreach ($nama as $key => $val) {
                    array_push($data, array(
                        'nama_posisi' => $this->request->getPost('nama_posisi')[$key],
                    ));
                }
                if ($this->posisim->insertBatch($data)) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Posisi Tersimpan';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->posisim->errors();
                }
                echo json_encode($status);
                break;
            case 'update':
                $id = $this->request->getPost('id');
                $data = array();
                foreach ($id as $key => $val) {
                    array_push($data, array(
                        'id' => $val,
                        'nama_posisi' => $this->request->getPost('nama_posisi')[$key],
                    ));
                }
                if ($this->posisim->updateBatch($data, 'id')) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Posisi Telah Di Ubah';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->posisim->errors();
                }
                echo json_encode($status);
                break;
            case 'delete':
                if ($this->posisim->delete($this->request->getPost('id'))) {
                    $status['type'] = 'success';
                    $status['text'] = '<strong>Deleted..!</strong>Berhasil dihapus';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = '<strong>Oh snap!</strong> Proses hapus data gagal.';
                }
                echo json_encode($status);
                break;
        }
    }
}

/* End of file Aspek.php */
/* Location: ./app/controllers/Aspek.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-31 08:03:25 */
/* http://harviacode.com */