<?php

namespace App\Models;

use CodeIgniter\Model;

class BeritaM extends Model
{
    protected $table = 'berita';
    protected $allowedFields = array('judul', 'slug', 'gambar', 'redaksi_foto', 'body', 'tanggal', 'user_id', 'editor', 'redaktur', 'tag', 'status', 'skpd_id');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = [
        'judul' => 'required|max_length[255]',
        'gambar' => 'required|max_length[100]',
        'redaksi_foto' => 'max_length[65535]',
        'body' => 'required|max_length[65535]',
        'tanggal' => 'required',
        'user_id' => 'required|max_length[100]',
        'editor' => 'max_length[100]',
        'redaktur' => 'max_length[100]',
        'tag' => 'max_length[160]',
    ];

    protected $validationMessages = [
        'judul' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 255 Karakter'],
        'gambar' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 100 Karakter'],
        'redaksi_foto' => ['max_length' => 'Maximal 65535 Karakter'],
        'body' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 65535 Karakter'],
        'tanggal' => ['required' => 'tidak boleh kosong'],
        'user_id' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 100 Karakter'],
        'editor' => ['max_length' => 'Maximal 100 Karakter'],
        'redaktur' => ['max_length' => 'Maximal 100 Karakter'],
        'tag' => ['max_length' => 'Maximal 160 Karakter'],
    ];
    private function _get_datatables($where)
    {
        $column_search = array('judul', 'gambar', 'redaksi_foto', 'body', 'tanggal', 'users.nama_user', 'tag', 'status');
        $i = 0;
        $this->select('berita.*, users.nama_user AS users');
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (!empty($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'desc');
        }
        $this->join('users','users.id = berita.user_id','INNER');
        $this->where($where);
    }
    public function get_datatables($where)
    {
        $this->_get_datatables($where);
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total($where)
    {
        $this->_get_datatables($where);
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file BeritaM.php */
/* Location: ./app/models/BeritaM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-31 04:44:35 */