<?php namespace App\Models;
use CodeIgniter\Model;
class InovasiM extends Model{ 
    protected $table = 'inovasi';
    protected $allowedFields = array('skpd_id','judul','inovasi', 'pdf', 'publisher');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = ['judul' => 'required|max_length[150]',
		'skpd_id' => 'required|max_length[1]',
		'inovasi' => 'required|max_length[350]',
			];

    protected $validationMessages = ['judul' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 150 Karakter'],
		'skpd_id' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 1 Karakter'],
		'inovasi' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 350 Karakter'],
		];
    private function _get_datatables(){
        $column_search = array('judul','inovasi');
        $i = 0;
        foreach ($column_search as $item){ // loop column 
            if($_GET['search']){
                if($i===0){
                    $this->groupStart(); 
                    $this->like($item,$_GET['search']);
                }else{
                    $this->orLike($item, $_GET['search']);
                }
                if(count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if(isset($_GET['order'])){
            $this->orderBy($_GET['sort'], $_GET['order']);
        }else{
            $this->orderBy('id', 'asc');
        }
        if (!in_groups([2])) {
            $this->where('skpd_id', session('skpd_id'));
        }
        $this->orderBy('id', 'desc');
        $this->select('inovasi.*,d.alias');
        $this->join('skpd d', 'd.id=inovasi.skpd_id');
    }
    public function get_datatables(){
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit,$offset);
    }
    public function total(){
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file InovasiM.php */
/* Location: ./app/models/InovasiM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-16 04:00:04 */