<?php

namespace App\Models;

use CodeIgniter\Model;

class Nilai_bobotM extends Model
{
    protected $table = 'nilai_bobot';
    protected $allowedFields = array('selisih', 'bobot_nilai', 'ket');
    protected $returnType     = 'object';

    protected $validationRules = [
        'selisih' => 'required|max_length[11]',
        'bobot_nilai' => 'required|max_length[4]',
        'ket' => 'required|max_length[150]',
    ];

    protected $validationMessages = [
        'selisih' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 11 Karakter'],
        'bobot_niali' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 4 Karakter'],
        'ket' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 150 Karakter'],
    ];
    private function _get_datatables()
    {
        $column_search = array('selisih', 'bobot_nilai', 'ket');
        $i = 0;
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (isset($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'asc');
        }
    }
    public function get_datatables()
    {
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total()
    {
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file Nilai_gapM.php */
/* Location: ./app/models/Nilai_gapM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-31 10:19:59 */