<?php

namespace App\Models;

use CodeIgniter\Model;

class StatistikM extends Model
{
    protected $table = 'statistik';
    protected $allowedFields = array('nik', 'desa', 'jk', 'tahun');
    protected $returnType     = 'object';

    protected $validationRules = [
        'nik' => 'required|max_length[18]',
        'jk' => 'required|max_length[1]',
        'tahun' => 'required|max_length[4]',
    ];

    protected $validationMessages = [
        'nik' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 18 Karakter'],
        'jk' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 1 Karakter'],
        'tahun' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 4 Karakter'],
    ];

    private function _get_datatables()
    {
        $column_search = array('tahun');
        $i = 0;
        foreach ($column_search as $item) { // loop column 
            if ($_GET['search']) {
                if ($i === 0) {
                    $this->groupStart();
                    $this->like($item, $_GET['search']);
                } else {
                    $this->orLike($item, $_GET['search']);
                }
                if (count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if (isset($_GET['order'])) {
            $this->orderBy($_GET['sort'], $_GET['order']);
        } else {
            $this->orderBy('id', 'asc');
        }
        $this->select('*');
        $this->selectCount('tahun', 'jumlah');
        $this->groupBy('tahun');
    }
    public function get_datatables()
    {
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit, $offset);
    }
    public function total()
    {
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file StatistikM.php */
/* Location: ./app/models/StatistikM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-08 04:07:43 */